name: Create Hello File

# ðŸ‘‡ Add this block to give write permissions to GITHUB_TOKEN
permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Create hello.txt with message
        run: echo "Hellow Hamid" > hello.txt

      - name: Commit and push file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ðŸ¤– Add hello.txt with greeting"
